# version: '3'
# services:
#   parser:
#     image: parser_image:latest
#     container_name: parser_service
#     restart: always
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#       - SCYLLA_HOST=localhost
#       - SCYLLA_PORT=9042
#       - SCYLLA_KEYSPACE=your_keyspace
#       - SCYLLA_USERNAME=sashabushuev03@mail.ru
#       - SCYLLA_PASSWORD=Bushuev2003!
#     depends_on:
#       - redis
#       - scylla

#   redis:
#     image: "redis:latest"
#     container_name: redis
#     ports:
#       - "6379:6379"
#     restart: always

#   scylla:
#     image: "scylladb/scylla:latest"
#     container_name: scylla
#     ports:
#       - "9042:9042"
#     restart: always
#     environment:
#       - SCYLLA_CLUSTER_NAME=ClusterName
#       - SCYLLA_DC=DataCenter
#       - SCYLLA_RACK=Rack
#       - SCYLLA_USERNAME=sashabushuev03@mail.ru
#       - SCYLLA_PASSWORD=Bushuev2003!

#   database:
#     image: database_image:latest
#     container_name: database_service
#     restart: always
#     environment:
#       - SCYLLA_HOST=scylla
#       - SCYLLA_PORT=9042
#       - SCYLLA_KEYSPACE=your_keyspace
#       - SCYLLA_USERNAME=sashabushuev03@mail.ru
#       - SCYLLA_PASSWORD=Bushuev2003!
#     depends_on:
#       - scylla
